### ISSUE TITLE
user-can-create-a-review-from-scratch

### ISSUE THREAD

**Issue by SheaPone** [SheaPone/front-end-project#1]
## ⚙️ Feature

User can create a review from scratch, no API

## 📐 Plan

Creates a responsive form that allows users to store an image URL, book title, author, rating, and review

## 🖼️ Wireframes

![user can create a review mobile](https://www.figma.com/design/tLyFggwW9uHB3ZPay0Q4KB/Shea-Pone---Front-End-Project?node-id=242-1961&m=dev&t=A3PoyFGH9lbnoZp1-1)
![user can create a review desktop](https://www.figma.com/design/tLyFggwW9uHB3ZPay0Q4KB/Shea-Pone---Front-End-Project?node-id=1-4&m=dev&t=A3PoyFGH9lbnoZp1-1)

## ✅ Task List

- [x] Add a `div[data-view="review"]` to the HTML.
- [x] Add a form for creating a review to the `div[data-view="review"]`.
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [x] Make all inputs of the review form `required`.
- [x] Listen for `'input'` events on the `photoUrl` input to update the `src` attribute of the photo preview when the input value changes.
- [x] add event listener to stars to change rating stars
- [x] Listen for `'submit'` events on the review form and:
  - [x] Put the form's input values into a new object.
  - [x] Add the `nextReviewId` to the object.
  - [x] Increment the `nextReviewId` on the data model.
  - [x] Prepend the new object to the revews in the data model.
  - [x] Reset the image preview's `src' attribute.
  - [x] Reset the form inputs.
- [x] Verify that new reviews are saved to local storage along with the rest of the data model on page reload.
- [x] Verify that each new review receives an incrementing `reviewId`.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
