### ISSUE TITLE
user-can-view-their-reviews 

### ISSUE THREAD

**Issue by SheaPone** [SheaPone/front-end-project#2]
## ⚙️ Feature

User can view their reviews in the my reviews tab

## 📐 Plan

Display the user's reviews in reverse chronological order so they can see the newest ones first.

## 🖼️ Wireframes

![user can create a review mobile](https://www.figma.com/design/tLyFggwW9uHB3ZPay0Q4KB/Shea-Pone---Front-End-Project?node-id=242-1961&m=dev&t=A3PoyFGH9lbnoZp1-1)
![user can create a review desktop](https://www.figma.com/design/tLyFggwW9uHB3ZPay0Q4KB/Shea-Pone---Front-End-Project?node-id=1-4&m=dev&t=A3PoyFGH9lbnoZp1-1)

## ✅ Task List

- [x] Add a sibling `div[data-view="reviews"]` to the HTML.
- [x] Add an empty unordered list to the `div[data-view="reviews"]` element in the HTML.
- [x] Add some dummy reviews to the unordered list in the HTML and style them to match the wireframe.
- [x] Check that the reviews list looks good on both mobile and desktop screens.
- [x] Define a function that takes a single 'review' object and returns a DOM tree that matches one of the example reviews in the HTML.
- [x] Use a loop to create a DOM tree for each review in the data model and append it to the page when the `'DOMContentLoaded'` event is fired.
- [x] Remove the example HTML reviews once the user's reviews are successfully being appended to the DOM on page load.
- [x] Ensure that submitting a new review also creates a new DOM tree for it and adds it to the page.
- [x] Ensure that submitting a new review automatically shows the `reviews` view without reloading the page.
- [x] Ensure that refreshing the pages shows the same view as before refreshing.
- [x] Clean up all unnecessary styling.
- [x] Test the app some more in a private browsing tab.
- [x] Fix all errors.
