### ISSUE TITLE
user-can-edit-their-review

### ISSUE THREAD

**Issue by SheaPone** [SheaPone/front-end-project#3]
## ⚙️ Feature

If a user makes a mistake when creating a review or wants to add more notes to a review, they should be able to edit it.

## 📐 Plan

Allow users to select an existing review to edit and pre-populate its information into the form.

## 🖼️ Wireframes

![user can create a review mobile](https://www.figma.com/design/tLyFggwW9uHB3ZPay0Q4KB/Shea-Pone---Front-End-Project?node-id=242-1961&m=dev&t=A3PoyFGH9lbnoZp1-1)
![user can create a review desktop](https://www.figma.com/design/tLyFggwW9uHB3ZPay0Q4KB/Shea-Pone---Front-End-Project?node-id=1-4&m=dev&t=A3PoyFGH9lbnoZp1-1)

## ✅ Task List

- [x] Update review rendering function to include an edit icon for each rendered review.
- [x] Ensure that each rendered review is given a `data-review-id` attribute indicating which review it is.
- [x] Listen for clicks on the parent element of all rendered reviews.
- [x] Show the review form if an edit icon was clicked.
- [x] Find the matching review object in the data model and assign it to the data model's `editing` property if an edit icon was clicked.
- [x] Pre-populate the review form with the clicked review's values from the object found in the data model.
- [x] Update the review form's submit handler function to conditionally add a new review object or update the existing one.
- [x] Update the review form's submit handler function to conditionally add a new review DOM tree or replace the existing one.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
