### ISSUE TITLE
user-can-delete-a-review

### ISSUE THREAD

**Issue by SheaPone** [SheaPone/front-end-project#4]
## ⚙️ Feature

If a user decides that they no longer wish to keep a review, they should be able to delete it.

## 📐 Plan

Allow users to delete a review from its edit screen.

## 🖼️ Wireframes

![user can create a review mobile](https://www.figma.com/design/tLyFggwW9uHB3ZPay0Q4KB/Shea-Pone---Front-End-Project?node-id=242-1961&m=dev&t=A3PoyFGH9lbnoZp1-1)
![user can create a review desktop](https://www.figma.com/design/tLyFggwW9uHB3ZPay0Q4KB/Shea-Pone---Front-End-Project?node-id=1-4&m=dev&t=A3PoyFGH9lbnoZp1-1)

## ✅ Task List

- [x] Add a click target for deleting a review to the review form that only appears if the user is editing a review.
- [x] Show a confirmation modal when the user clicks the Delete review click target.
- [x] Hide the modal if the user clicks Cancel.
- [x] Remove the review from the data model and the review's DOM tree from the page if the user clicks Delete.
- [x] Show the reviews list if the user clicks Delete.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
