### ISSUE TITLE
user-can-search-for-books

### ISSUE THREAD

**Issue by SheaPone** [SheaPone/front-end-project#5]
## ⚙️ Feature

A user can search from a list of books to write a review

## 📐 Plan

Allow users to search through list of books and pre-populate form with title, author, and photoURL

## 🖼️ Wireframes

![user can create a review mobile](https://www.figma.com/design/tLyFggwW9uHB3ZPay0Q4KB/Shea-Pone---Front-End-Project?node-id=242-1961&m=dev&t=A3PoyFGH9lbnoZp1-1)
![user can create a review desktop](https://www.figma.com/design/tLyFggwW9uHB3ZPay0Q4KB/Shea-Pone---Front-End-Project?node-id=1-4&m=dev&t=A3PoyFGH9lbnoZp1-1)

## ✅ Task List

- [ ] Add a sibling `div[data-view="home"]` to the HTML.
- [ ] Check that the home page looks good on both mobile and desktop screens.
- [ ] Fetch API link for google books every time user inputs search
- [ ] Define a function that fetch API link for google books every time user inputs something in search bar
- [ ] modal opens when search is occurring
- [ ] create UI that shows waiting when book is being searched for
- [ ] when user clicks on book, title, author and thumbnail from fetch is pre-populated in form
- [ ] user should be taken to form page created in issue #1 
- [ ] Clean up all unnecessary styling.
- [ ] Test the app some more in a private browsing tab.
- [ ] Fix all errors.
