### ISSUE TITLE
user-can-search-through-my-reviews

### ISSUE THREAD

**Issue by SheaPone** [SheaPone/front-end-project#6]
## ⚙️ Feature

User should be able to search through reviews of specific book

## 📐 Plan

Allow users to search through their own reviews

## 🖼️ Wireframes

![user can create a review mobile](https://www.figma.com/design/tLyFggwW9uHB3ZPay0Q4KB/Shea-Pone---Front-End-Project?node-id=242-1961&m=dev&t=A3PoyFGH9lbnoZp1-1)
![user can create a review desktop](https://www.figma.com/design/tLyFggwW9uHB3ZPay0Q4KB/Shea-Pone---Front-End-Project?node-id=1-4&m=dev&t=A3PoyFGH9lbnoZp1-1)

## ✅ Task List

- [x] Add search bar on my reviews page
- [x] ensure it has data-search in input
- [x] query the DOM for data-search
- [x] create function that takes event target and searches through data-review-id for key words found in search
- [x] add event listener for 'input'
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
